names = ["Jack", "Mr Sheehan", "Bob", "Alice", "Roxy", "Joe", "George", "Ellie"]
print("Names: ", names)
print("Length: ", len(names))
names.append("Sam")
names.append("Ben")
names.append("Julie")
print(names[3])
print(names[5])
print(names[10])
names[3] = names[2].upper()
names[5] = names[4].upper()
names[10] = names[9].upper()
print(names[3])
print(names[5])
print(names[10])